// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: broadcasts.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countBroadcastStatsActive = `-- name: CountBroadcastStatsActive :one
SELECT COUNT(*)
FROM broadcast_stats
WHERE active = TRUE
`

func (q *Queries) CountBroadcastStatsActive(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBroadcastStatsActive)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBroadcastStatsTotal = `-- name: CountBroadcastStatsTotal :one
SELECT COUNT(*)
FROM broadcast_stats
`

func (q *Queries) CountBroadcastStatsTotal(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBroadcastStatsTotal)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBroadcastTarget = `-- name: CreateBroadcastTarget :exec
INSERT INTO broadcast_targets (
  broadcast_id,
  user_id,
  sort_order,
  status,
  error,
  updated_at
) VALUES (?, ?, ?, 'pending', '', ?)
ON CONFLICT(broadcast_id, user_id) DO NOTHING
`

type CreateBroadcastTargetParams struct {
	BroadcastID int64  `db:"broadcast_id" json:"broadcast_id"`
	UserID      string `db:"user_id" json:"user_id"`
	SortOrder   int64  `db:"sort_order" json:"sort_order"`
	UpdatedAt   string `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateBroadcastTarget(ctx context.Context, arg CreateBroadcastTargetParams) error {
	_, err := q.db.ExecContext(ctx, createBroadcastTarget,
		arg.BroadcastID,
		arg.UserID,
		arg.SortOrder,
		arg.UpdatedAt,
	)
	return err
}

const finishBroadcastStats = `-- name: FinishBroadcastStats :exec
UPDATE broadcast_stats
SET
  active = FALSE,
  status = ?,
  updated_at = ?,
  finished_at = ?
WHERE id = ?
`

type FinishBroadcastStatsParams struct {
	Status     string         `db:"status" json:"status"`
	UpdatedAt  string         `db:"updated_at" json:"updated_at"`
	FinishedAt sql.NullString `db:"finished_at" json:"finished_at"`
	ID         int64          `db:"id" json:"id"`
}

func (q *Queries) FinishBroadcastStats(ctx context.Context, arg FinishBroadcastStatsParams) error {
	_, err := q.db.ExecContext(ctx, finishBroadcastStats,
		arg.Status,
		arg.UpdatedAt,
		arg.FinishedAt,
		arg.ID,
	)
	return err
}

const getBroadcastStats = `-- name: GetBroadcastStats :one
SELECT
  id,
  date,
  type,
  total,
  success,
  error,
  active,
  status,
  stop_requested,
  admin_chat_id,
  payload_json,
  created_at,
  updated_at,
  finished_at
FROM broadcast_stats
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetBroadcastStats(ctx context.Context, id int64) (BroadcastStat, error) {
	row := q.db.QueryRowContext(ctx, getBroadcastStats, id)
	var i BroadcastStat
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Type,
		&i.Total,
		&i.Success,
		&i.Error,
		&i.Active,
		&i.Status,
		&i.StopRequested,
		&i.AdminChatID,
		&i.PayloadJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const incBroadcastError = `-- name: IncBroadcastError :exec
UPDATE broadcast_stats
SET
  error = error + 1,
  updated_at = ?
WHERE id = ?
`

type IncBroadcastErrorParams struct {
	UpdatedAt string `db:"updated_at" json:"updated_at"`
	ID        int64  `db:"id" json:"id"`
}

func (q *Queries) IncBroadcastError(ctx context.Context, arg IncBroadcastErrorParams) error {
	_, err := q.db.ExecContext(ctx, incBroadcastError, arg.UpdatedAt, arg.ID)
	return err
}

const incBroadcastSuccess = `-- name: IncBroadcastSuccess :exec
UPDATE broadcast_stats
SET
  success = success + 1,
  updated_at = ?
WHERE id = ?
`

type IncBroadcastSuccessParams struct {
	UpdatedAt string `db:"updated_at" json:"updated_at"`
	ID        int64  `db:"id" json:"id"`
}

func (q *Queries) IncBroadcastSuccess(ctx context.Context, arg IncBroadcastSuccessParams) error {
	_, err := q.db.ExecContext(ctx, incBroadcastSuccess, arg.UpdatedAt, arg.ID)
	return err
}

const listActiveBroadcastStats = `-- name: ListActiveBroadcastStats :many
SELECT
  id,
  date,
  type,
  total,
  success,
  error,
  active,
  status,
  stop_requested,
  admin_chat_id,
  payload_json,
  created_at,
  updated_at,
  finished_at
FROM broadcast_stats
WHERE active = TRUE
ORDER BY created_at DESC
`

func (q *Queries) ListActiveBroadcastStats(ctx context.Context) ([]BroadcastStat, error) {
	rows, err := q.db.QueryContext(ctx, listActiveBroadcastStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BroadcastStat
	for rows.Next() {
		var i BroadcastStat
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Type,
			&i.Total,
			&i.Success,
			&i.Error,
			&i.Active,
			&i.Status,
			&i.StopRequested,
			&i.AdminChatID,
			&i.PayloadJson,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBroadcastStats = `-- name: ListBroadcastStats :many
SELECT
  id,
  date,
  type,
  total,
  success,
  error,
  active,
  status,
  stop_requested,
  admin_chat_id,
  payload_json,
  created_at,
  updated_at,
  finished_at
FROM broadcast_stats
ORDER BY created_at DESC
LIMIT ?
`

func (q *Queries) ListBroadcastStats(ctx context.Context, limit int64) ([]BroadcastStat, error) {
	rows, err := q.db.QueryContext(ctx, listBroadcastStats, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BroadcastStat
	for rows.Next() {
		var i BroadcastStat
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Type,
			&i.Total,
			&i.Success,
			&i.Error,
			&i.Active,
			&i.Status,
			&i.StopRequested,
			&i.AdminChatID,
			&i.PayloadJson,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingBroadcastTargets = `-- name: ListPendingBroadcastTargets :many
SELECT
  broadcast_id,
  user_id,
  sort_order,
  status,
  error,
  updated_at
FROM broadcast_targets
WHERE broadcast_id = ?
  AND status = 'pending'
ORDER BY sort_order
LIMIT ?
`

type ListPendingBroadcastTargetsParams struct {
	BroadcastID int64 `db:"broadcast_id" json:"broadcast_id"`
	Limit       int64 `db:"limit" json:"limit"`
}

func (q *Queries) ListPendingBroadcastTargets(ctx context.Context, arg ListPendingBroadcastTargetsParams) ([]BroadcastTarget, error) {
	rows, err := q.db.QueryContext(ctx, listPendingBroadcastTargets, arg.BroadcastID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BroadcastTarget
	for rows.Next() {
		var i BroadcastTarget
		if err := rows.Scan(
			&i.BroadcastID,
			&i.UserID,
			&i.SortOrder,
			&i.Status,
			&i.Error,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResumableBroadcastStats = `-- name: ListResumableBroadcastStats :many
SELECT
  id,
  date,
  type,
  total,
  success,
  error,
  active,
  status,
  stop_requested,
  admin_chat_id,
  payload_json,
  created_at,
  updated_at,
  finished_at
FROM broadcast_stats
WHERE active = TRUE
ORDER BY created_at ASC
`

func (q *Queries) ListResumableBroadcastStats(ctx context.Context) ([]BroadcastStat, error) {
	rows, err := q.db.QueryContext(ctx, listResumableBroadcastStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BroadcastStat
	for rows.Next() {
		var i BroadcastStat
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Type,
			&i.Total,
			&i.Success,
			&i.Error,
			&i.Active,
			&i.Status,
			&i.StopRequested,
			&i.AdminChatID,
			&i.PayloadJson,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBroadcastTargetError = `-- name: MarkBroadcastTargetError :execrows
UPDATE broadcast_targets
SET
  status = 'error',
  error = ?,
  updated_at = ?
WHERE broadcast_id = ?
  AND user_id = ?
  AND status = 'pending'
`

type MarkBroadcastTargetErrorParams struct {
	Error       string `db:"error" json:"error"`
	UpdatedAt   string `db:"updated_at" json:"updated_at"`
	BroadcastID int64  `db:"broadcast_id" json:"broadcast_id"`
	UserID      string `db:"user_id" json:"user_id"`
}

func (q *Queries) MarkBroadcastTargetError(ctx context.Context, arg MarkBroadcastTargetErrorParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markBroadcastTargetError,
		arg.Error,
		arg.UpdatedAt,
		arg.BroadcastID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markBroadcastTargetSent = `-- name: MarkBroadcastTargetSent :execrows
UPDATE broadcast_targets
SET
  status = 'sent',
  error = '',
  updated_at = ?
WHERE broadcast_id = ?
  AND user_id = ?
  AND status = 'pending'
`

type MarkBroadcastTargetSentParams struct {
	UpdatedAt   string `db:"updated_at" json:"updated_at"`
	BroadcastID int64  `db:"broadcast_id" json:"broadcast_id"`
	UserID      string `db:"user_id" json:"user_id"`
}

func (q *Queries) MarkBroadcastTargetSent(ctx context.Context, arg MarkBroadcastTargetSentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markBroadcastTargetSent, arg.UpdatedAt, arg.BroadcastID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const requestStopBroadcastStats = `-- name: RequestStopBroadcastStats :execrows
UPDATE broadcast_stats
SET
  status = 'cancel_requested',
  stop_requested = TRUE,
  updated_at = ?
WHERE id = ?
  AND active = TRUE
`

type RequestStopBroadcastStatsParams struct {
	UpdatedAt string `db:"updated_at" json:"updated_at"`
	ID        int64  `db:"id" json:"id"`
}

func (q *Queries) RequestStopBroadcastStats(ctx context.Context, arg RequestStopBroadcastStatsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, requestStopBroadcastStats, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const startBroadcastStats = `-- name: StartBroadcastStats :one
INSERT INTO broadcast_stats (
  date,
  type,
  total,
  success,
  error,
  active,
  status,
  stop_requested,
  admin_chat_id,
  payload_json,
  created_at,
  updated_at
) VALUES (?, ?, ?, 0, 0, TRUE, 'running', FALSE, ?, ?, ?, ?)
RETURNING id, date, type, total, success, error, active, status, stop_requested, admin_chat_id, payload_json, created_at, updated_at, finished_at
`

type StartBroadcastStatsParams struct {
	Date        string `db:"date" json:"date"`
	Type        string `db:"type" json:"type"`
	Total       int64  `db:"total" json:"total"`
	AdminChatID string `db:"admin_chat_id" json:"admin_chat_id"`
	PayloadJson string `db:"payload_json" json:"payload_json"`
	CreatedAt   string `db:"created_at" json:"created_at"`
	UpdatedAt   string `db:"updated_at" json:"updated_at"`
}

func (q *Queries) StartBroadcastStats(ctx context.Context, arg StartBroadcastStatsParams) (BroadcastStat, error) {
	row := q.db.QueryRowContext(ctx, startBroadcastStats,
		arg.Date,
		arg.Type,
		arg.Total,
		arg.AdminChatID,
		arg.PayloadJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i BroadcastStat
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Type,
		&i.Total,
		&i.Success,
		&i.Error,
		&i.Active,
		&i.Status,
		&i.StopRequested,
		&i.AdminChatID,
		&i.PayloadJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}
