// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: integration_tokens.sql

package sqlc

import (
	"context"
)

const createIntegrationToken = `-- name: CreateIntegrationToken :one
INSERT INTO integration_tokens (
  provider,
  token,
  created_at,
  updated_at
) VALUES (?, ?, ?, ?)
RETURNING id, provider, token, created_at, updated_at
`

type CreateIntegrationTokenParams struct {
	Provider  string `db:"provider" json:"provider"`
	Token     string `db:"token" json:"token"`
	CreatedAt string `db:"created_at" json:"created_at"`
	UpdatedAt string `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateIntegrationToken(ctx context.Context, arg CreateIntegrationTokenParams) (IntegrationToken, error) {
	row := q.db.QueryRowContext(ctx, createIntegrationToken,
		arg.Provider,
		arg.Token,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i IntegrationToken
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIntegrationToken = `-- name: DeleteIntegrationToken :execrows
DELETE FROM integration_tokens
WHERE id = ?
  AND provider = ?
`

type DeleteIntegrationTokenParams struct {
	ID       int64  `db:"id" json:"id"`
	Provider string `db:"provider" json:"provider"`
}

func (q *Queries) DeleteIntegrationToken(ctx context.Context, arg DeleteIntegrationTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteIntegrationToken, arg.ID, arg.Provider)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getIntegrationTokenByID = `-- name: GetIntegrationTokenByID :one
SELECT
  id,
  provider,
  token,
  created_at,
  updated_at
FROM integration_tokens
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetIntegrationTokenByID(ctx context.Context, id int64) (IntegrationToken, error) {
	row := q.db.QueryRowContext(ctx, getIntegrationTokenByID, id)
	var i IntegrationToken
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIntegrationTokensByProvider = `-- name: ListIntegrationTokensByProvider :many
SELECT
  id,
  provider,
  token,
  created_at,
  updated_at
FROM integration_tokens
WHERE provider = ?
ORDER BY id DESC
`

func (q *Queries) ListIntegrationTokensByProvider(ctx context.Context, provider string) ([]IntegrationToken, error) {
	rows, err := q.db.QueryContext(ctx, listIntegrationTokensByProvider, provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IntegrationToken
	for rows.Next() {
		var i IntegrationToken
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Token,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIntegrationToken = `-- name: UpdateIntegrationToken :execrows
UPDATE integration_tokens
SET
  token = ?,
  updated_at = ?
WHERE id = ?
  AND provider = ?
`

type UpdateIntegrationTokenParams struct {
	Token     string `db:"token" json:"token"`
	UpdatedAt string `db:"updated_at" json:"updated_at"`
	ID        int64  `db:"id" json:"id"`
	Provider  string `db:"provider" json:"provider"`
}

func (q *Queries) UpdateIntegrationToken(ctx context.Context, arg UpdateIntegrationTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateIntegrationToken,
		arg.Token,
		arg.UpdatedAt,
		arg.ID,
		arg.Provider,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
