// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mandatory.sql

package sqlc

import (
	"context"
)

const claimMandatoryRewardProgress = `-- name: ClaimMandatoryRewardProgress :execrows
INSERT INTO mandatory_reward_progress (
  channel_row_id,
  user_id,
  processed_at
) VALUES (?, ?, ?)
ON CONFLICT(channel_row_id, user_id) DO NOTHING
`

type ClaimMandatoryRewardProgressParams struct {
	ChannelRowID int64  `db:"channel_row_id" json:"channel_row_id"`
	UserID       string `db:"user_id" json:"user_id"`
	ProcessedAt  string `db:"processed_at" json:"processed_at"`
}

func (q *Queries) ClaimMandatoryRewardProgress(ctx context.Context, arg ClaimMandatoryRewardProgressParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimMandatoryRewardProgress, arg.ChannelRowID, arg.UserID, arg.ProcessedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createMandatoryChannel = `-- name: CreateMandatoryChannel :one
INSERT INTO mandatory_channels (
  channel_id,
  title,
  url,
  requires_check,
  active,
  created_at
) VALUES (?, ?, ?, ?, TRUE, ?)
RETURNING id, channel_id, title, url, requires_check, active, created_at
`

type CreateMandatoryChannelParams struct {
	ChannelID     string `db:"channel_id" json:"channel_id"`
	Title         string `db:"title" json:"title"`
	Url           string `db:"url" json:"url"`
	RequiresCheck bool   `db:"requires_check" json:"requires_check"`
	CreatedAt     string `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateMandatoryChannel(ctx context.Context, arg CreateMandatoryChannelParams) (MandatoryChannel, error) {
	row := q.db.QueryRowContext(ctx, createMandatoryChannel,
		arg.ChannelID,
		arg.Title,
		arg.Url,
		arg.RequiresCheck,
		arg.CreatedAt,
	)
	var i MandatoryChannel
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Title,
		&i.Url,
		&i.RequiresCheck,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMandatoryChannel = `-- name: DeleteMandatoryChannel :exec
DELETE FROM mandatory_channels
WHERE id = ?
`

func (q *Queries) DeleteMandatoryChannel(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMandatoryChannel, id)
	return err
}

const getMandatoryChannel = `-- name: GetMandatoryChannel :one
SELECT id, channel_id, title, url, requires_check, active, created_at
FROM mandatory_channels
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetMandatoryChannel(ctx context.Context, id int64) (MandatoryChannel, error) {
	row := q.db.QueryRowContext(ctx, getMandatoryChannel, id)
	var i MandatoryChannel
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Title,
		&i.Url,
		&i.RequiresCheck,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const listMandatoryChannels = `-- name: ListMandatoryChannels :many
SELECT id, channel_id, title, url, requires_check, active, created_at
FROM mandatory_channels
WHERE active = TRUE
ORDER BY id
`

func (q *Queries) ListMandatoryChannels(ctx context.Context) ([]MandatoryChannel, error) {
	rows, err := q.db.QueryContext(ctx, listMandatoryChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MandatoryChannel
	for rows.Next() {
		var i MandatoryChannel
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Title,
			&i.Url,
			&i.RequiresCheck,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersPendingMandatoryReward = `-- name: ListUsersPendingMandatoryReward :many
SELECT u.user_id
FROM users u
LEFT JOIN user_mandatory_status s
  ON s.user_id = u.user_id
 AND s.channel_row_id = ?
LEFT JOIN mandatory_reward_progress p
  ON p.channel_row_id = ?
 AND p.user_id = u.user_id
WHERE COALESCE(s.subscribed, FALSE) = FALSE
  AND p.user_id IS NULL
ORDER BY u.user_id
`

type ListUsersPendingMandatoryRewardParams struct {
	ChannelRowID   int64 `db:"channel_row_id" json:"channel_row_id"`
	ChannelRowID_2 int64 `db:"channel_row_id_2" json:"channel_row_id_2"`
}

func (q *Queries) ListUsersPendingMandatoryReward(ctx context.Context, arg ListUsersPendingMandatoryRewardParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listUsersPendingMandatoryReward, arg.ChannelRowID, arg.ChannelRowID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseMandatoryRewardProgress = `-- name: ReleaseMandatoryRewardProgress :exec
DELETE FROM mandatory_reward_progress
WHERE channel_row_id = ?
  AND user_id = ?
`

type ReleaseMandatoryRewardProgressParams struct {
	ChannelRowID int64  `db:"channel_row_id" json:"channel_row_id"`
	UserID       string `db:"user_id" json:"user_id"`
}

func (q *Queries) ReleaseMandatoryRewardProgress(ctx context.Context, arg ReleaseMandatoryRewardProgressParams) error {
	_, err := q.db.ExecContext(ctx, releaseMandatoryRewardProgress, arg.ChannelRowID, arg.UserID)
	return err
}

const resetMandatoryRewardProgress = `-- name: ResetMandatoryRewardProgress :exec
DELETE FROM mandatory_reward_progress
WHERE channel_row_id = ?
`

func (q *Queries) ResetMandatoryRewardProgress(ctx context.Context, channelRowID int64) error {
	_, err := q.db.ExecContext(ctx, resetMandatoryRewardProgress, channelRowID)
	return err
}

const upsertMandatorySubscription = `-- name: UpsertMandatorySubscription :exec
INSERT INTO user_mandatory_status (
  user_id,
  channel_row_id,
  subscribed,
  updated_at
) VALUES (?, ?, ?, ?)
ON CONFLICT(user_id, channel_row_id) DO UPDATE SET
  subscribed = excluded.subscribed,
  updated_at = excluded.updated_at
`

type UpsertMandatorySubscriptionParams struct {
	UserID       string `db:"user_id" json:"user_id"`
	ChannelRowID int64  `db:"channel_row_id" json:"channel_row_id"`
	Subscribed   bool   `db:"subscribed" json:"subscribed"`
	UpdatedAt    string `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpsertMandatorySubscription(ctx context.Context, arg UpsertMandatorySubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, upsertMandatorySubscription,
		arg.UserID,
		arg.ChannelRowID,
		arg.Subscribed,
		arg.UpdatedAt,
	)
	return err
}
