// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metrics.sql

package sqlc

import (
	"context"
)

const countMetricEventsBetween = `-- name: CountMetricEventsBetween :one
SELECT COUNT(*)
FROM metric_events
WHERE kind = ?
  AND created_at >= ?
  AND created_at < ?
`

type CountMetricEventsBetweenParams struct {
	Kind        string `db:"kind" json:"kind"`
	CreatedAt   string `db:"created_at" json:"created_at"`
	CreatedAt_2 string `db:"created_at_2" json:"created_at_2"`
}

func (q *Queries) CountMetricEventsBetween(ctx context.Context, arg CountMetricEventsBetweenParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMetricEventsBetween, arg.Kind, arg.CreatedAt, arg.CreatedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMetricEventsTotal = `-- name: CountMetricEventsTotal :one
SELECT COUNT(*)
FROM metric_events
WHERE kind = ?
`

func (q *Queries) CountMetricEventsTotal(ctx context.Context, kind string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMetricEventsTotal, kind)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReferredUsersBetween = `-- name: CountReferredUsersBetween :one
SELECT COUNT(*)
FROM users
WHERE referral_by != ''
  AND created_at >= ?
  AND created_at < ?
`

type CountReferredUsersBetweenParams struct {
	CreatedAt   string `db:"created_at" json:"created_at"`
	CreatedAt_2 string `db:"created_at_2" json:"created_at_2"`
}

func (q *Queries) CountReferredUsersBetween(ctx context.Context, arg CountReferredUsersBetweenParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReferredUsersBetween, arg.CreatedAt, arg.CreatedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReferredUsersTotal = `-- name: CountReferredUsersTotal :one
SELECT COUNT(*)
FROM users
WHERE referral_by != ''
`

func (q *Queries) CountReferredUsersTotal(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReferredUsersTotal)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersCreatedBetween = `-- name: CountUsersCreatedBetween :one
SELECT COUNT(*)
FROM users
WHERE created_at >= ?
  AND created_at < ?
`

type CountUsersCreatedBetweenParams struct {
	CreatedAt   string `db:"created_at" json:"created_at"`
	CreatedAt_2 string `db:"created_at_2" json:"created_at_2"`
}

func (q *Queries) CountUsersCreatedBetween(ctx context.Context, arg CountUsersCreatedBetweenParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsersCreatedBetween, arg.CreatedAt, arg.CreatedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersTotal = `-- name: CountUsersTotal :one
SELECT COUNT(*)
FROM users
`

func (q *Queries) CountUsersTotal(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsersTotal)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersUpdatedBetween = `-- name: CountUsersUpdatedBetween :one
SELECT COUNT(*)
FROM users
WHERE updated_at >= ?
  AND updated_at < ?
`

type CountUsersUpdatedBetweenParams struct {
	UpdatedAt   string `db:"updated_at" json:"updated_at"`
	UpdatedAt_2 string `db:"updated_at_2" json:"updated_at_2"`
}

func (q *Queries) CountUsersUpdatedBetween(ctx context.Context, arg CountUsersUpdatedBetweenParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsersUpdatedBetween, arg.UpdatedAt, arg.UpdatedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMetricEvent = `-- name: CreateMetricEvent :exec
INSERT INTO metric_events (
  kind,
  user_id,
  ref_id,
  value,
  created_at
) VALUES (?, ?, ?, ?, ?)
`

type CreateMetricEventParams struct {
	Kind      string `db:"kind" json:"kind"`
	UserID    string `db:"user_id" json:"user_id"`
	RefID     int64  `db:"ref_id" json:"ref_id"`
	Value     int64  `db:"value" json:"value"`
	CreatedAt string `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateMetricEvent(ctx context.Context, arg CreateMetricEventParams) error {
	_, err := q.db.ExecContext(ctx, createMetricEvent,
		arg.Kind,
		arg.UserID,
		arg.RefID,
		arg.Value,
		arg.CreatedAt,
	)
	return err
}
