// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type BroadcastStat struct {
	ID            int64          `db:"id" json:"id"`
	Date          string         `db:"date" json:"date"`
	Type          string         `db:"type" json:"type"`
	Total         int64          `db:"total" json:"total"`
	Success       int64          `db:"success" json:"success"`
	Error         int64          `db:"error" json:"error"`
	Active        bool           `db:"active" json:"active"`
	Status        string         `db:"status" json:"status"`
	StopRequested bool           `db:"stop_requested" json:"stop_requested"`
	AdminChatID   string         `db:"admin_chat_id" json:"admin_chat_id"`
	PayloadJson   string         `db:"payload_json" json:"payload_json"`
	CreatedAt     string         `db:"created_at" json:"created_at"`
	UpdatedAt     string         `db:"updated_at" json:"updated_at"`
	FinishedAt    sql.NullString `db:"finished_at" json:"finished_at"`
}

type BroadcastTarget struct {
	BroadcastID int64  `db:"broadcast_id" json:"broadcast_id"`
	UserID      string `db:"user_id" json:"user_id"`
	SortOrder   int64  `db:"sort_order" json:"sort_order"`
	Status      string `db:"status" json:"status"`
	Error       string `db:"error" json:"error"`
	UpdatedAt   string `db:"updated_at" json:"updated_at"`
}

type IntegrationToken struct {
	ID        int64  `db:"id" json:"id"`
	Provider  string `db:"provider" json:"provider"`
	Token     string `db:"token" json:"token"`
	CreatedAt string `db:"created_at" json:"created_at"`
	UpdatedAt string `db:"updated_at" json:"updated_at"`
}

type MandatoryChannel struct {
	ID            int64  `db:"id" json:"id"`
	ChannelID     string `db:"channel_id" json:"channel_id"`
	Title         string `db:"title" json:"title"`
	Url           string `db:"url" json:"url"`
	RequiresCheck bool   `db:"requires_check" json:"requires_check"`
	Active        bool   `db:"active" json:"active"`
	CreatedAt     string `db:"created_at" json:"created_at"`
}

type MandatoryRewardProgress struct {
	ChannelRowID int64  `db:"channel_row_id" json:"channel_row_id"`
	UserID       string `db:"user_id" json:"user_id"`
	ProcessedAt  string `db:"processed_at" json:"processed_at"`
}

type MetricEvent struct {
	ID        int64  `db:"id" json:"id"`
	Kind      string `db:"kind" json:"kind"`
	UserID    string `db:"user_id" json:"user_id"`
	RefID     int64  `db:"ref_id" json:"ref_id"`
	Value     int64  `db:"value" json:"value"`
	CreatedAt string `db:"created_at" json:"created_at"`
}

type PaymentTransaction struct {
	ID             int64          `db:"id" json:"id"`
	TransactionID  string         `db:"transaction_id" json:"transaction_id"`
	UserID         string         `db:"user_id" json:"user_id"`
	PlatformUserID string         `db:"platform_user_id" json:"platform_user_id"`
	ProductKey     string         `db:"product_key" json:"product_key"`
	ProductTitle   string         `db:"product_title" json:"product_title"`
	Coins          int64          `db:"coins" json:"coins"`
	Amount         int64          `db:"amount" json:"amount"`
	Currency       string         `db:"currency" json:"currency"`
	PaymentMethod  int64          `db:"payment_method" json:"payment_method"`
	Status         string         `db:"status" json:"status"`
	RedirectUrl    string         `db:"redirect_url" json:"redirect_url"`
	Rewarded       bool           `db:"rewarded" json:"rewarded"`
	PaidAt         sql.NullString `db:"paid_at" json:"paid_at"`
	CreatedAt      string         `db:"created_at" json:"created_at"`
	UpdatedAt      string         `db:"updated_at" json:"updated_at"`
}

type Post struct {
	ID          int64  `db:"id" json:"id"`
	Title       string `db:"title" json:"title"`
	Text        string `db:"text" json:"text"`
	MediaID     string `db:"media_id" json:"media_id"`
	MediaKind   string `db:"media_kind" json:"media_kind"`
	ButtonsJson string `db:"buttons_json" json:"buttons_json"`
	CreatedBy   string `db:"created_by" json:"created_by"`
	CreatedAt   string `db:"created_at" json:"created_at"`
}

type PostDelivery struct {
	PostID int64  `db:"post_id" json:"post_id"`
	UserID string `db:"user_id" json:"user_id"`
	Status string `db:"status" json:"status"`
	Error  string `db:"error" json:"error"`
	SentAt string `db:"sent_at" json:"sent_at"`
}

type Task struct {
	ID        int64  `db:"id" json:"id"`
	Reward    int64  `db:"reward" json:"reward"`
	Active    bool   `db:"active" json:"active"`
	CreatedAt string `db:"created_at" json:"created_at"`
	UpdatedAt string `db:"updated_at" json:"updated_at"`
}

type TaskChannel struct {
	ID            int64  `db:"id" json:"id"`
	TaskID        int64  `db:"task_id" json:"task_id"`
	ChannelID     string `db:"channel_id" json:"channel_id"`
	Title         string `db:"title" json:"title"`
	Url           string `db:"url" json:"url"`
	RequiresCheck bool   `db:"requires_check" json:"requires_check"`
	SortOrder     int64  `db:"sort_order" json:"sort_order"`
	CreatedAt     string `db:"created_at" json:"created_at"`
	UpdatedAt     string `db:"updated_at" json:"updated_at"`
}

type TaskReward struct {
	TaskID     int64  `db:"task_id" json:"task_id"`
	UserID     string `db:"user_id" json:"user_id"`
	Reward     int64  `db:"reward" json:"reward"`
	RewardedAt string `db:"rewarded_at" json:"rewarded_at"`
}

type TrackLink struct {
	ID              int64  `db:"id" json:"id"`
	Code            string `db:"code" json:"code"`
	Label           string `db:"label" json:"label"`
	CreatedByUserID string `db:"created_by_user_id" json:"created_by_user_id"`
	CreatedAt       string `db:"created_at" json:"created_at"`
}

type TrackLinkGeneratedUser struct {
	UserID      string `db:"user_id" json:"user_id"`
	LinkID      int64  `db:"link_id" json:"link_id"`
	GeneratedAt string `db:"generated_at" json:"generated_at"`
}

type TrackLinkStat struct {
	LinkID              int64  `db:"link_id" json:"link_id"`
	ArrivalsCount       int64  `db:"arrivals_count" json:"arrivals_count"`
	GeneratedUsersCount int64  `db:"generated_users_count" json:"generated_users_count"`
	UpdatedAt           string `db:"updated_at" json:"updated_at"`
}

type TrackLinkVisit struct {
	ID        int64  `db:"id" json:"id"`
	UserID    string `db:"user_id" json:"user_id"`
	LinkID    int64  `db:"link_id" json:"link_id"`
	VisitedAt string `db:"visited_at" json:"visited_at"`
}

type User struct {
	UserID                 string  `db:"user_id" json:"user_id"`
	Name                   string  `db:"name" json:"name"`
	BirthDate              string  `db:"birth_date" json:"birth_date"`
	Theme                  string  `db:"theme" json:"theme"`
	Coins                  int64   `db:"coins" json:"coins"`
	Detailed               bool    `db:"detailed" json:"detailed"`
	DailyCardDate          string  `db:"daily_card_date" json:"daily_card_date"`
	DailyCardStreak        int64   `db:"daily_card_streak" json:"daily_card_streak"`
	DailyReminderDate      string  `db:"daily_reminder_date" json:"daily_reminder_date"`
	ReferralBy             string  `db:"referral_by" json:"referral_by"`
	ReferralCnt            int64   `db:"referral_cnt" json:"referral_cnt"`
	ReferralRewardProgress float64 `db:"referral_reward_progress" json:"referral_reward_progress"`
	CreatedAt              string  `db:"created_at" json:"created_at"`
	UpdatedAt              string  `db:"updated_at" json:"updated_at"`
}

type UserMandatoryStatus struct {
	UserID       string `db:"user_id" json:"user_id"`
	ChannelRowID int64  `db:"channel_row_id" json:"channel_row_id"`
	Subscribed   bool   `db:"subscribed" json:"subscribed"`
	UpdatedAt    string `db:"updated_at" json:"updated_at"`
}
