// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createPaymentTransaction = `-- name: CreatePaymentTransaction :one
INSERT INTO payment_transactions (
  transaction_id,
  user_id,
  platform_user_id,
  product_key,
  product_title,
  coins,
  amount,
  currency,
  payment_method,
  status,
  redirect_url,
  rewarded,
  paid_at,
  created_at,
  updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, transaction_id, user_id, platform_user_id, product_key, product_title, coins, amount, currency, payment_method, status, redirect_url, rewarded, paid_at, created_at, updated_at
`

type CreatePaymentTransactionParams struct {
	TransactionID  string         `db:"transaction_id" json:"transaction_id"`
	UserID         string         `db:"user_id" json:"user_id"`
	PlatformUserID string         `db:"platform_user_id" json:"platform_user_id"`
	ProductKey     string         `db:"product_key" json:"product_key"`
	ProductTitle   string         `db:"product_title" json:"product_title"`
	Coins          int64          `db:"coins" json:"coins"`
	Amount         int64          `db:"amount" json:"amount"`
	Currency       string         `db:"currency" json:"currency"`
	PaymentMethod  int64          `db:"payment_method" json:"payment_method"`
	Status         string         `db:"status" json:"status"`
	RedirectUrl    string         `db:"redirect_url" json:"redirect_url"`
	Rewarded       bool           `db:"rewarded" json:"rewarded"`
	PaidAt         sql.NullString `db:"paid_at" json:"paid_at"`
	CreatedAt      string         `db:"created_at" json:"created_at"`
	UpdatedAt      string         `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreatePaymentTransaction(ctx context.Context, arg CreatePaymentTransactionParams) (PaymentTransaction, error) {
	row := q.db.QueryRowContext(ctx, createPaymentTransaction,
		arg.TransactionID,
		arg.UserID,
		arg.PlatformUserID,
		arg.ProductKey,
		arg.ProductTitle,
		arg.Coins,
		arg.Amount,
		arg.Currency,
		arg.PaymentMethod,
		arg.Status,
		arg.RedirectUrl,
		arg.Rewarded,
		arg.PaidAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i PaymentTransaction
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.UserID,
		&i.PlatformUserID,
		&i.ProductKey,
		&i.ProductTitle,
		&i.Coins,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.Status,
		&i.RedirectUrl,
		&i.Rewarded,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentTransactionByID = `-- name: GetPaymentTransactionByID :one
SELECT
  id,
  transaction_id,
  user_id,
  platform_user_id,
  product_key,
  product_title,
  coins,
  amount,
  currency,
  payment_method,
  status,
  redirect_url,
  rewarded,
  paid_at,
  created_at,
  updated_at
FROM payment_transactions
WHERE transaction_id = ?
LIMIT 1
`

func (q *Queries) GetPaymentTransactionByID(ctx context.Context, transactionID string) (PaymentTransaction, error) {
	row := q.db.QueryRowContext(ctx, getPaymentTransactionByID, transactionID)
	var i PaymentTransaction
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.UserID,
		&i.PlatformUserID,
		&i.ProductKey,
		&i.ProductTitle,
		&i.Coins,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.Status,
		&i.RedirectUrl,
		&i.Rewarded,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markPaymentTransactionRewarded = `-- name: MarkPaymentTransactionRewarded :exec
UPDATE payment_transactions
SET
  rewarded = TRUE,
  updated_at = ?
WHERE transaction_id = ?
`

type MarkPaymentTransactionRewardedParams struct {
	UpdatedAt     string `db:"updated_at" json:"updated_at"`
	TransactionID string `db:"transaction_id" json:"transaction_id"`
}

func (q *Queries) MarkPaymentTransactionRewarded(ctx context.Context, arg MarkPaymentTransactionRewardedParams) error {
	_, err := q.db.ExecContext(ctx, markPaymentTransactionRewarded, arg.UpdatedAt, arg.TransactionID)
	return err
}

const markPaymentTransactionStatus = `-- name: MarkPaymentTransactionStatus :exec
UPDATE payment_transactions
SET
  status = ?,
  payment_method = ?,
  paid_at = ?,
  updated_at = ?
WHERE transaction_id = ?
`

type MarkPaymentTransactionStatusParams struct {
	Status        string         `db:"status" json:"status"`
	PaymentMethod int64          `db:"payment_method" json:"payment_method"`
	PaidAt        sql.NullString `db:"paid_at" json:"paid_at"`
	UpdatedAt     string         `db:"updated_at" json:"updated_at"`
	TransactionID string         `db:"transaction_id" json:"transaction_id"`
}

func (q *Queries) MarkPaymentTransactionStatus(ctx context.Context, arg MarkPaymentTransactionStatusParams) error {
	_, err := q.db.ExecContext(ctx, markPaymentTransactionStatus,
		arg.Status,
		arg.PaymentMethod,
		arg.PaidAt,
		arg.UpdatedAt,
		arg.TransactionID,
	)
	return err
}
