// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package sqlc

import (
	"context"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (
  title,
  text,
  media_id,
  media_kind,
  buttons_json,
  created_by,
  created_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, title, text, media_id, media_kind, buttons_json, created_by, created_at
`

type CreatePostParams struct {
	Title       string `db:"title" json:"title"`
	Text        string `db:"text" json:"text"`
	MediaID     string `db:"media_id" json:"media_id"`
	MediaKind   string `db:"media_kind" json:"media_kind"`
	ButtonsJson string `db:"buttons_json" json:"buttons_json"`
	CreatedBy   string `db:"created_by" json:"created_by"`
	CreatedAt   string `db:"created_at" json:"created_at"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.Title,
		arg.Text,
		arg.MediaID,
		arg.MediaKind,
		arg.ButtonsJson,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Text,
		&i.MediaID,
		&i.MediaKind,
		&i.ButtonsJson,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getPost = `-- name: GetPost :one
SELECT id, title, text, media_id, media_kind, buttons_json, created_by, created_at
FROM posts
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetPost(ctx context.Context, id int64) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Text,
		&i.MediaID,
		&i.MediaKind,
		&i.ButtonsJson,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listPosts = `-- name: ListPosts :many
SELECT id, title, text, media_id, media_kind, buttons_json, created_by, created_at
FROM posts
ORDER BY id DESC
`

func (q *Queries) ListPosts(ctx context.Context) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Text,
			&i.MediaID,
			&i.MediaKind,
			&i.ButtonsJson,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const savePostDelivery = `-- name: SavePostDelivery :exec
INSERT INTO post_deliveries (
  post_id,
  user_id,
  status,
  error,
  sent_at
) VALUES (?, ?, ?, ?, ?)
ON CONFLICT(post_id, user_id) DO UPDATE SET
  status = excluded.status,
  error = excluded.error,
  sent_at = excluded.sent_at
`

type SavePostDeliveryParams struct {
	PostID int64  `db:"post_id" json:"post_id"`
	UserID string `db:"user_id" json:"user_id"`
	Status string `db:"status" json:"status"`
	Error  string `db:"error" json:"error"`
	SentAt string `db:"sent_at" json:"sent_at"`
}

func (q *Queries) SavePostDelivery(ctx context.Context, arg SavePostDeliveryParams) error {
	_, err := q.db.ExecContext(ctx, savePostDelivery,
		arg.PostID,
		arg.UserID,
		arg.Status,
		arg.Error,
		arg.SentAt,
	)
	return err
}
