// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	AddUserCoins(ctx context.Context, arg AddUserCoinsParams) error
	ClaimMandatoryRewardProgress(ctx context.Context, arg ClaimMandatoryRewardProgressParams) (int64, error)
	CountBroadcastStatsActive(ctx context.Context) (int64, error)
	CountBroadcastStatsTotal(ctx context.Context) (int64, error)
	CountMetricEventsBetween(ctx context.Context, arg CountMetricEventsBetweenParams) (int64, error)
	CountMetricEventsTotal(ctx context.Context, kind string) (int64, error)
	CountReferredUsersBetween(ctx context.Context, arg CountReferredUsersBetweenParams) (int64, error)
	CountReferredUsersTotal(ctx context.Context) (int64, error)
	CountTaskRewardForUser(ctx context.Context, arg CountTaskRewardForUserParams) (int64, error)
	CountTrackVisitsBetween(ctx context.Context, arg CountTrackVisitsBetweenParams) (int64, error)
	CountTrackVisitsTotal(ctx context.Context) (int64, error)
	CountUsersCreatedBetween(ctx context.Context, arg CountUsersCreatedBetweenParams) (int64, error)
	CountUsersTotal(ctx context.Context) (int64, error)
	CountUsersUpdatedBetween(ctx context.Context, arg CountUsersUpdatedBetweenParams) (int64, error)
	CreateBroadcastTarget(ctx context.Context, arg CreateBroadcastTargetParams) error
	CreateIntegrationToken(ctx context.Context, arg CreateIntegrationTokenParams) (IntegrationToken, error)
	CreateMandatoryChannel(ctx context.Context, arg CreateMandatoryChannelParams) (MandatoryChannel, error)
	CreateMetricEvent(ctx context.Context, arg CreateMetricEventParams) error
	CreatePaymentTransaction(ctx context.Context, arg CreatePaymentTransactionParams) (PaymentTransaction, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateTrackLink(ctx context.Context, arg CreateTrackLinkParams) (TrackLink, error)
	CreateTrackLinkStats(ctx context.Context, arg CreateTrackLinkStatsParams) error
	CreateUserIfMissing(ctx context.Context, arg CreateUserIfMissingParams) error
	DeleteIntegrationToken(ctx context.Context, arg DeleteIntegrationTokenParams) (int64, error)
	DeleteMandatoryChannel(ctx context.Context, id int64) error
	DeleteTaskChannelsByTaskID(ctx context.Context, taskID int64) error
	DeleteTrackLink(ctx context.Context, id int64) error
	FinishBroadcastStats(ctx context.Context, arg FinishBroadcastStatsParams) error
	GetBroadcastStats(ctx context.Context, id int64) (BroadcastStat, error)
	GetIntegrationTokenByID(ctx context.Context, id int64) (IntegrationToken, error)
	GetMandatoryChannel(ctx context.Context, id int64) (MandatoryChannel, error)
	GetPaymentTransactionByID(ctx context.Context, transactionID string) (PaymentTransaction, error)
	GetPost(ctx context.Context, id int64) (Post, error)
	GetTask(ctx context.Context, id int64) (Task, error)
	GetTaskWithStats(ctx context.Context, arg GetTaskWithStatsParams) (GetTaskWithStatsRow, error)
	GetTrackLink(ctx context.Context, id int64) (GetTrackLinkRow, error)
	GetTrackLinkByCode(ctx context.Context, code string) (GetTrackLinkByCodeRow, error)
	GetUser(ctx context.Context, userID string) (User, error)
	IncBroadcastError(ctx context.Context, arg IncBroadcastErrorParams) error
	IncBroadcastSuccess(ctx context.Context, arg IncBroadcastSuccessParams) error
	IncrementTrackArrivals(ctx context.Context, arg IncrementTrackArrivalsParams) error
	IncrementTrackGeneratedUsers(ctx context.Context, arg IncrementTrackGeneratedUsersParams) error
	IncrementUserReferralCount(ctx context.Context, arg IncrementUserReferralCountParams) error
	InsertTaskChannel(ctx context.Context, arg InsertTaskChannelParams) error
	InsertTaskReward(ctx context.Context, arg InsertTaskRewardParams) (int64, error)
	InsertTrackGeneratedUser(ctx context.Context, arg InsertTrackGeneratedUserParams) (int64, error)
	InsertTrackVisit(ctx context.Context, arg InsertTrackVisitParams) (int64, error)
	ListActiveBroadcastStats(ctx context.Context) ([]BroadcastStat, error)
	ListBroadcastStats(ctx context.Context, limit int64) ([]BroadcastStat, error)
	ListIntegrationTokensByProvider(ctx context.Context, provider string) ([]IntegrationToken, error)
	ListMandatoryChannels(ctx context.Context) ([]MandatoryChannel, error)
	ListPendingBroadcastTargets(ctx context.Context, arg ListPendingBroadcastTargetsParams) ([]BroadcastTarget, error)
	ListPosts(ctx context.Context) ([]Post, error)
	ListResumableBroadcastStats(ctx context.Context) ([]BroadcastStat, error)
	ListTaskChannelsByTaskID(ctx context.Context, taskID int64) ([]TaskChannel, error)
	ListTasksWithStats(ctx context.Context, arg ListTasksWithStatsParams) ([]ListTasksWithStatsRow, error)
	ListTrackLinks(ctx context.Context) ([]ListTrackLinksRow, error)
	ListUserIDs(ctx context.Context) ([]string, error)
	ListUsers(ctx context.Context) ([]User, error)
	ListUsersPendingMandatoryReward(ctx context.Context, arg ListUsersPendingMandatoryRewardParams) ([]string, error)
	MarkBroadcastTargetError(ctx context.Context, arg MarkBroadcastTargetErrorParams) (int64, error)
	MarkBroadcastTargetSent(ctx context.Context, arg MarkBroadcastTargetSentParams) (int64, error)
	MarkPaymentTransactionRewarded(ctx context.Context, arg MarkPaymentTransactionRewardedParams) error
	MarkPaymentTransactionStatus(ctx context.Context, arg MarkPaymentTransactionStatusParams) error
	RegisterUserReferral(ctx context.Context, arg RegisterUserReferralParams) (int64, error)
	ReleaseMandatoryRewardProgress(ctx context.Context, arg ReleaseMandatoryRewardProgressParams) error
	RequestStopBroadcastStats(ctx context.Context, arg RequestStopBroadcastStatsParams) (int64, error)
	ResetMandatoryRewardProgress(ctx context.Context, channelRowID int64) error
	SavePostDelivery(ctx context.Context, arg SavePostDeliveryParams) error
	SetTaskActive(ctx context.Context, arg SetTaskActiveParams) (int64, error)
	SpendUserCoins(ctx context.Context, arg SpendUserCoinsParams) (int64, error)
	StartBroadcastStats(ctx context.Context, arg StartBroadcastStatsParams) (BroadcastStat, error)
	TouchUser(ctx context.Context, arg TouchUserParams) error
	UpdateIntegrationToken(ctx context.Context, arg UpdateIntegrationTokenParams) (int64, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (int64, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error
	UpdateUserReferralRewardProgress(ctx context.Context, arg UpdateUserReferralRewardProgressParams) error
	UpdateUserTheme(ctx context.Context, arg UpdateUserThemeParams) error
	UpsertMandatorySubscription(ctx context.Context, arg UpsertMandatorySubscriptionParams) error
}

var _ Querier = (*Queries)(nil)
