// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package sqlc

import (
	"context"
)

const countTaskRewardForUser = `-- name: CountTaskRewardForUser :one
SELECT COUNT(*)
FROM task_rewards
WHERE task_id = ?
  AND user_id = ?
`

type CountTaskRewardForUserParams struct {
	TaskID int64  `db:"task_id" json:"task_id"`
	UserID string `db:"user_id" json:"user_id"`
}

func (q *Queries) CountTaskRewardForUser(ctx context.Context, arg CountTaskRewardForUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTaskRewardForUser, arg.TaskID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
  reward,
  active,
  created_at,
  updated_at
) VALUES (?, ?, ?, ?)
RETURNING id, reward, active, created_at, updated_at
`

type CreateTaskParams struct {
	Reward    int64  `db:"reward" json:"reward"`
	Active    bool   `db:"active" json:"active"`
	CreatedAt string `db:"created_at" json:"created_at"`
	UpdatedAt string `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.Reward,
		arg.Active,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Reward,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTaskChannelsByTaskID = `-- name: DeleteTaskChannelsByTaskID :exec
DELETE FROM task_channels
WHERE task_id = ?
`

func (q *Queries) DeleteTaskChannelsByTaskID(ctx context.Context, taskID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTaskChannelsByTaskID, taskID)
	return err
}

const getTask = `-- name: GetTask :one
SELECT
  id,
  reward,
  active,
  created_at,
  updated_at
FROM tasks
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetTask(ctx context.Context, id int64) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Reward,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskWithStats = `-- name: GetTaskWithStats :one
SELECT
  t.id,
  t.reward,
  t.active,
  t.created_at,
  t.updated_at,
  CAST(COALESCE((
    SELECT COUNT(*)
    FROM task_rewards tr
    WHERE tr.task_id = t.id
  ), 0) AS INTEGER) AS completed_total,
  CAST(COALESCE((
    SELECT COUNT(*)
    FROM task_rewards tr
    WHERE tr.task_id = t.id
      AND tr.rewarded_at >= ?
      AND tr.rewarded_at < ?
  ), 0) AS INTEGER) AS completed_today,
  CAST(COALESCE((
    SELECT COUNT(*)
    FROM task_rewards tr
    WHERE tr.task_id = t.id
      AND tr.rewarded_at >= ?
      AND tr.rewarded_at < ?
  ), 0) AS INTEGER) AS completed_yesterday
FROM tasks t
WHERE t.id = ?
LIMIT 1
`

type GetTaskWithStatsParams struct {
	RewardedAt   string `db:"rewarded_at" json:"rewarded_at"`
	RewardedAt_2 string `db:"rewarded_at_2" json:"rewarded_at_2"`
	RewardedAt_3 string `db:"rewarded_at_3" json:"rewarded_at_3"`
	RewardedAt_4 string `db:"rewarded_at_4" json:"rewarded_at_4"`
	ID           int64  `db:"id" json:"id"`
}

type GetTaskWithStatsRow struct {
	ID                 int64  `db:"id" json:"id"`
	Reward             int64  `db:"reward" json:"reward"`
	Active             bool   `db:"active" json:"active"`
	CreatedAt          string `db:"created_at" json:"created_at"`
	UpdatedAt          string `db:"updated_at" json:"updated_at"`
	CompletedTotal     int64  `db:"completed_total" json:"completed_total"`
	CompletedToday     int64  `db:"completed_today" json:"completed_today"`
	CompletedYesterday int64  `db:"completed_yesterday" json:"completed_yesterday"`
}

func (q *Queries) GetTaskWithStats(ctx context.Context, arg GetTaskWithStatsParams) (GetTaskWithStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getTaskWithStats,
		arg.RewardedAt,
		arg.RewardedAt_2,
		arg.RewardedAt_3,
		arg.RewardedAt_4,
		arg.ID,
	)
	var i GetTaskWithStatsRow
	err := row.Scan(
		&i.ID,
		&i.Reward,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedTotal,
		&i.CompletedToday,
		&i.CompletedYesterday,
	)
	return i, err
}

const insertTaskChannel = `-- name: InsertTaskChannel :exec
INSERT INTO task_channels (
  task_id,
  channel_id,
  title,
  url,
  requires_check,
  sort_order,
  created_at,
  updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertTaskChannelParams struct {
	TaskID        int64  `db:"task_id" json:"task_id"`
	ChannelID     string `db:"channel_id" json:"channel_id"`
	Title         string `db:"title" json:"title"`
	Url           string `db:"url" json:"url"`
	RequiresCheck bool   `db:"requires_check" json:"requires_check"`
	SortOrder     int64  `db:"sort_order" json:"sort_order"`
	CreatedAt     string `db:"created_at" json:"created_at"`
	UpdatedAt     string `db:"updated_at" json:"updated_at"`
}

func (q *Queries) InsertTaskChannel(ctx context.Context, arg InsertTaskChannelParams) error {
	_, err := q.db.ExecContext(ctx, insertTaskChannel,
		arg.TaskID,
		arg.ChannelID,
		arg.Title,
		arg.Url,
		arg.RequiresCheck,
		arg.SortOrder,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertTaskReward = `-- name: InsertTaskReward :execrows
INSERT OR IGNORE INTO task_rewards (
  task_id,
  user_id,
  reward,
  rewarded_at
) VALUES (?, ?, ?, ?)
`

type InsertTaskRewardParams struct {
	TaskID     int64  `db:"task_id" json:"task_id"`
	UserID     string `db:"user_id" json:"user_id"`
	Reward     int64  `db:"reward" json:"reward"`
	RewardedAt string `db:"rewarded_at" json:"rewarded_at"`
}

func (q *Queries) InsertTaskReward(ctx context.Context, arg InsertTaskRewardParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertTaskReward,
		arg.TaskID,
		arg.UserID,
		arg.Reward,
		arg.RewardedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listTaskChannelsByTaskID = `-- name: ListTaskChannelsByTaskID :many
SELECT
  id,
  task_id,
  channel_id,
  title,
  url,
  requires_check,
  sort_order,
  created_at,
  updated_at
FROM task_channels
WHERE task_id = ?
ORDER BY sort_order ASC, id ASC
`

func (q *Queries) ListTaskChannelsByTaskID(ctx context.Context, taskID int64) ([]TaskChannel, error) {
	rows, err := q.db.QueryContext(ctx, listTaskChannelsByTaskID, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskChannel
	for rows.Next() {
		var i TaskChannel
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ChannelID,
			&i.Title,
			&i.Url,
			&i.RequiresCheck,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksWithStats = `-- name: ListTasksWithStats :many
SELECT
  t.id,
  t.reward,
  t.active,
  t.created_at,
  t.updated_at,
  CAST(COALESCE((
    SELECT COUNT(*)
    FROM task_rewards tr
    WHERE tr.task_id = t.id
  ), 0) AS INTEGER) AS completed_total,
  CAST(COALESCE((
    SELECT COUNT(*)
    FROM task_rewards tr
    WHERE tr.task_id = t.id
      AND tr.rewarded_at >= ?
      AND tr.rewarded_at < ?
  ), 0) AS INTEGER) AS completed_today,
  CAST(COALESCE((
    SELECT COUNT(*)
    FROM task_rewards tr
    WHERE tr.task_id = t.id
      AND tr.rewarded_at >= ?
      AND tr.rewarded_at < ?
  ), 0) AS INTEGER) AS completed_yesterday
FROM tasks t
WHERE t.active = TRUE
ORDER BY t.id ASC
`

type ListTasksWithStatsParams struct {
	RewardedAt   string `db:"rewarded_at" json:"rewarded_at"`
	RewardedAt_2 string `db:"rewarded_at_2" json:"rewarded_at_2"`
	RewardedAt_3 string `db:"rewarded_at_3" json:"rewarded_at_3"`
	RewardedAt_4 string `db:"rewarded_at_4" json:"rewarded_at_4"`
}

type ListTasksWithStatsRow struct {
	ID                 int64  `db:"id" json:"id"`
	Reward             int64  `db:"reward" json:"reward"`
	Active             bool   `db:"active" json:"active"`
	CreatedAt          string `db:"created_at" json:"created_at"`
	UpdatedAt          string `db:"updated_at" json:"updated_at"`
	CompletedTotal     int64  `db:"completed_total" json:"completed_total"`
	CompletedToday     int64  `db:"completed_today" json:"completed_today"`
	CompletedYesterday int64  `db:"completed_yesterday" json:"completed_yesterday"`
}

func (q *Queries) ListTasksWithStats(ctx context.Context, arg ListTasksWithStatsParams) ([]ListTasksWithStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTasksWithStats,
		arg.RewardedAt,
		arg.RewardedAt_2,
		arg.RewardedAt_3,
		arg.RewardedAt_4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTasksWithStatsRow
	for rows.Next() {
		var i ListTasksWithStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Reward,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedTotal,
			&i.CompletedToday,
			&i.CompletedYesterday,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTaskActive = `-- name: SetTaskActive :execrows
UPDATE tasks
SET
  active = ?,
  updated_at = ?
WHERE id = ?
`

type SetTaskActiveParams struct {
	Active    bool   `db:"active" json:"active"`
	UpdatedAt string `db:"updated_at" json:"updated_at"`
	ID        int64  `db:"id" json:"id"`
}

func (q *Queries) SetTaskActive(ctx context.Context, arg SetTaskActiveParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setTaskActive, arg.Active, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTask = `-- name: UpdateTask :execrows
UPDATE tasks
SET
  reward = ?,
  active = ?,
  updated_at = ?
WHERE id = ?
`

type UpdateTaskParams struct {
	Reward    int64  `db:"reward" json:"reward"`
	Active    bool   `db:"active" json:"active"`
	UpdatedAt string `db:"updated_at" json:"updated_at"`
	ID        int64  `db:"id" json:"id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTask,
		arg.Reward,
		arg.Active,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
