// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: track.sql

package sqlc

import (
	"context"
)

const countTrackVisitsBetween = `-- name: CountTrackVisitsBetween :one
SELECT COUNT(*)
FROM track_link_visits
WHERE visited_at >= ?
  AND visited_at < ?
`

type CountTrackVisitsBetweenParams struct {
	VisitedAt   string `db:"visited_at" json:"visited_at"`
	VisitedAt_2 string `db:"visited_at_2" json:"visited_at_2"`
}

func (q *Queries) CountTrackVisitsBetween(ctx context.Context, arg CountTrackVisitsBetweenParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTrackVisitsBetween, arg.VisitedAt, arg.VisitedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTrackVisitsTotal = `-- name: CountTrackVisitsTotal :one
SELECT COUNT(*)
FROM track_link_visits
`

func (q *Queries) CountTrackVisitsTotal(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTrackVisitsTotal)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTrackLink = `-- name: CreateTrackLink :one
INSERT INTO track_links (
  code,
  label,
  created_by_user_id,
  created_at
) VALUES (?, ?, ?, ?)
RETURNING id, code, label, created_by_user_id, created_at
`

type CreateTrackLinkParams struct {
	Code            string `db:"code" json:"code"`
	Label           string `db:"label" json:"label"`
	CreatedByUserID string `db:"created_by_user_id" json:"created_by_user_id"`
	CreatedAt       string `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateTrackLink(ctx context.Context, arg CreateTrackLinkParams) (TrackLink, error) {
	row := q.db.QueryRowContext(ctx, createTrackLink,
		arg.Code,
		arg.Label,
		arg.CreatedByUserID,
		arg.CreatedAt,
	)
	var i TrackLink
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Label,
		&i.CreatedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const createTrackLinkStats = `-- name: CreateTrackLinkStats :exec
INSERT INTO track_link_stats (
  link_id,
  arrivals_count,
  generated_users_count,
  updated_at
) VALUES (?, 0, 0, ?)
`

type CreateTrackLinkStatsParams struct {
	LinkID    int64  `db:"link_id" json:"link_id"`
	UpdatedAt string `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateTrackLinkStats(ctx context.Context, arg CreateTrackLinkStatsParams) error {
	_, err := q.db.ExecContext(ctx, createTrackLinkStats, arg.LinkID, arg.UpdatedAt)
	return err
}

const deleteTrackLink = `-- name: DeleteTrackLink :exec
DELETE FROM track_links
WHERE id = ?
`

func (q *Queries) DeleteTrackLink(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTrackLink, id)
	return err
}

const getTrackLink = `-- name: GetTrackLink :one
SELECT
  l.id,
  l.code,
  l.label,
  l.created_by_user_id,
  l.created_at,
  COALESCE(s.arrivals_count, 0) AS arrivals_count,
  COALESCE(s.generated_users_count, 0) AS generated_users_count
FROM track_links l
LEFT JOIN track_link_stats s ON s.link_id = l.id
WHERE l.id = ?
LIMIT 1
`

type GetTrackLinkRow struct {
	ID                  int64  `db:"id" json:"id"`
	Code                string `db:"code" json:"code"`
	Label               string `db:"label" json:"label"`
	CreatedByUserID     string `db:"created_by_user_id" json:"created_by_user_id"`
	CreatedAt           string `db:"created_at" json:"created_at"`
	ArrivalsCount       int64  `db:"arrivals_count" json:"arrivals_count"`
	GeneratedUsersCount int64  `db:"generated_users_count" json:"generated_users_count"`
}

func (q *Queries) GetTrackLink(ctx context.Context, id int64) (GetTrackLinkRow, error) {
	row := q.db.QueryRowContext(ctx, getTrackLink, id)
	var i GetTrackLinkRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Label,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.ArrivalsCount,
		&i.GeneratedUsersCount,
	)
	return i, err
}

const getTrackLinkByCode = `-- name: GetTrackLinkByCode :one
SELECT
  l.id,
  l.code,
  l.label,
  l.created_by_user_id,
  l.created_at,
  COALESCE(s.arrivals_count, 0) AS arrivals_count,
  COALESCE(s.generated_users_count, 0) AS generated_users_count
FROM track_links l
LEFT JOIN track_link_stats s ON s.link_id = l.id
WHERE l.code = ?
LIMIT 1
`

type GetTrackLinkByCodeRow struct {
	ID                  int64  `db:"id" json:"id"`
	Code                string `db:"code" json:"code"`
	Label               string `db:"label" json:"label"`
	CreatedByUserID     string `db:"created_by_user_id" json:"created_by_user_id"`
	CreatedAt           string `db:"created_at" json:"created_at"`
	ArrivalsCount       int64  `db:"arrivals_count" json:"arrivals_count"`
	GeneratedUsersCount int64  `db:"generated_users_count" json:"generated_users_count"`
}

func (q *Queries) GetTrackLinkByCode(ctx context.Context, code string) (GetTrackLinkByCodeRow, error) {
	row := q.db.QueryRowContext(ctx, getTrackLinkByCode, code)
	var i GetTrackLinkByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Label,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.ArrivalsCount,
		&i.GeneratedUsersCount,
	)
	return i, err
}

const incrementTrackArrivals = `-- name: IncrementTrackArrivals :exec
UPDATE track_link_stats
SET
  arrivals_count = arrivals_count + 1,
  updated_at = ?
WHERE link_id = ?
`

type IncrementTrackArrivalsParams struct {
	UpdatedAt string `db:"updated_at" json:"updated_at"`
	LinkID    int64  `db:"link_id" json:"link_id"`
}

func (q *Queries) IncrementTrackArrivals(ctx context.Context, arg IncrementTrackArrivalsParams) error {
	_, err := q.db.ExecContext(ctx, incrementTrackArrivals, arg.UpdatedAt, arg.LinkID)
	return err
}

const incrementTrackGeneratedUsers = `-- name: IncrementTrackGeneratedUsers :exec
UPDATE track_link_stats
SET
  generated_users_count = generated_users_count + 1,
  updated_at = ?
WHERE link_id = ?
`

type IncrementTrackGeneratedUsersParams struct {
	UpdatedAt string `db:"updated_at" json:"updated_at"`
	LinkID    int64  `db:"link_id" json:"link_id"`
}

func (q *Queries) IncrementTrackGeneratedUsers(ctx context.Context, arg IncrementTrackGeneratedUsersParams) error {
	_, err := q.db.ExecContext(ctx, incrementTrackGeneratedUsers, arg.UpdatedAt, arg.LinkID)
	return err
}

const insertTrackGeneratedUser = `-- name: InsertTrackGeneratedUser :execrows
INSERT OR IGNORE INTO track_link_generated_users (
  user_id,
  link_id,
  generated_at
) VALUES (?, ?, ?)
`

type InsertTrackGeneratedUserParams struct {
	UserID      string `db:"user_id" json:"user_id"`
	LinkID      int64  `db:"link_id" json:"link_id"`
	GeneratedAt string `db:"generated_at" json:"generated_at"`
}

func (q *Queries) InsertTrackGeneratedUser(ctx context.Context, arg InsertTrackGeneratedUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertTrackGeneratedUser, arg.UserID, arg.LinkID, arg.GeneratedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertTrackVisit = `-- name: InsertTrackVisit :execrows
INSERT OR IGNORE INTO track_link_visits (
  user_id,
  link_id,
  visited_at
) VALUES (?, ?, ?)
`

type InsertTrackVisitParams struct {
	UserID    string `db:"user_id" json:"user_id"`
	LinkID    int64  `db:"link_id" json:"link_id"`
	VisitedAt string `db:"visited_at" json:"visited_at"`
}

func (q *Queries) InsertTrackVisit(ctx context.Context, arg InsertTrackVisitParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertTrackVisit, arg.UserID, arg.LinkID, arg.VisitedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listTrackLinks = `-- name: ListTrackLinks :many
SELECT
  l.id,
  l.code,
  l.label,
  l.created_by_user_id,
  l.created_at,
  COALESCE(s.arrivals_count, 0) AS arrivals_count,
  COALESCE(s.generated_users_count, 0) AS generated_users_count
FROM track_links l
LEFT JOIN track_link_stats s ON s.link_id = l.id
ORDER BY l.id DESC
`

type ListTrackLinksRow struct {
	ID                  int64  `db:"id" json:"id"`
	Code                string `db:"code" json:"code"`
	Label               string `db:"label" json:"label"`
	CreatedByUserID     string `db:"created_by_user_id" json:"created_by_user_id"`
	CreatedAt           string `db:"created_at" json:"created_at"`
	ArrivalsCount       int64  `db:"arrivals_count" json:"arrivals_count"`
	GeneratedUsersCount int64  `db:"generated_users_count" json:"generated_users_count"`
}

func (q *Queries) ListTrackLinks(ctx context.Context) ([]ListTrackLinksRow, error) {
	rows, err := q.db.QueryContext(ctx, listTrackLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTrackLinksRow
	for rows.Next() {
		var i ListTrackLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Label,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.ArrivalsCount,
			&i.GeneratedUsersCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
