// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
)

const addUserCoins = `-- name: AddUserCoins :exec
UPDATE users
SET
  coins = coins + ?,
  updated_at = ?
WHERE user_id = ?
`

type AddUserCoinsParams struct {
	Coins     int64  `db:"coins" json:"coins"`
	UpdatedAt string `db:"updated_at" json:"updated_at"`
	UserID    string `db:"user_id" json:"user_id"`
}

func (q *Queries) AddUserCoins(ctx context.Context, arg AddUserCoinsParams) error {
	_, err := q.db.ExecContext(ctx, addUserCoins, arg.Coins, arg.UpdatedAt, arg.UserID)
	return err
}

const createUserIfMissing = `-- name: CreateUserIfMissing :exec
INSERT INTO users (
  user_id,
  coins,
  created_at,
  updated_at
) VALUES (?, ?, ?, ?)
ON CONFLICT(user_id) DO NOTHING
`

type CreateUserIfMissingParams struct {
	UserID    string `db:"user_id" json:"user_id"`
	Coins     int64  `db:"coins" json:"coins"`
	CreatedAt string `db:"created_at" json:"created_at"`
	UpdatedAt string `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateUserIfMissing(ctx context.Context, arg CreateUserIfMissingParams) error {
	_, err := q.db.ExecContext(ctx, createUserIfMissing,
		arg.UserID,
		arg.Coins,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getUser = `-- name: GetUser :one
SELECT
  user_id,
  name,
  birth_date,
  theme,
  coins,
  detailed,
  daily_card_date,
  daily_card_streak,
  daily_reminder_date,
  referral_by,
  referral_cnt,
  referral_reward_progress,
  created_at,
  updated_at
FROM users
WHERE user_id = ?
LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, userID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.BirthDate,
		&i.Theme,
		&i.Coins,
		&i.Detailed,
		&i.DailyCardDate,
		&i.DailyCardStreak,
		&i.DailyReminderDate,
		&i.ReferralBy,
		&i.ReferralCnt,
		&i.ReferralRewardProgress,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementUserReferralCount = `-- name: IncrementUserReferralCount :exec
UPDATE users
SET
  referral_cnt = referral_cnt + 1,
  updated_at = ?
WHERE user_id = ?
`

type IncrementUserReferralCountParams struct {
	UpdatedAt string `db:"updated_at" json:"updated_at"`
	UserID    string `db:"user_id" json:"user_id"`
}

func (q *Queries) IncrementUserReferralCount(ctx context.Context, arg IncrementUserReferralCountParams) error {
	_, err := q.db.ExecContext(ctx, incrementUserReferralCount, arg.UpdatedAt, arg.UserID)
	return err
}

const listUserIDs = `-- name: ListUserIDs :many
SELECT user_id
FROM users
ORDER BY created_at
`

func (q *Queries) ListUserIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listUserIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT
  user_id,
  name,
  birth_date,
  theme,
  coins,
  detailed,
  daily_card_date,
  daily_card_streak,
  daily_reminder_date,
  referral_by,
  referral_cnt,
  referral_reward_progress,
  created_at,
  updated_at
FROM users
ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.BirthDate,
			&i.Theme,
			&i.Coins,
			&i.Detailed,
			&i.DailyCardDate,
			&i.DailyCardStreak,
			&i.DailyReminderDate,
			&i.ReferralBy,
			&i.ReferralCnt,
			&i.ReferralRewardProgress,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerUserReferral = `-- name: RegisterUserReferral :execrows
UPDATE users
SET
  referral_by = ?,
  updated_at = ?
WHERE user_id = ?
  AND referral_by = ''
  AND user_id <> ?
`

type RegisterUserReferralParams struct {
	ReferralBy string `db:"referral_by" json:"referral_by"`
	UpdatedAt  string `db:"updated_at" json:"updated_at"`
	UserID     string `db:"user_id" json:"user_id"`
	UserID_2   string `db:"user_id_2" json:"user_id_2"`
}

func (q *Queries) RegisterUserReferral(ctx context.Context, arg RegisterUserReferralParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, registerUserReferral,
		arg.ReferralBy,
		arg.UpdatedAt,
		arg.UserID,
		arg.UserID_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const spendUserCoins = `-- name: SpendUserCoins :execrows
UPDATE users
SET
  coins = coins - ?,
  updated_at = ?
WHERE user_id = ?
  AND coins >= ?
`

type SpendUserCoinsParams struct {
	Coins     int64  `db:"coins" json:"coins"`
	UpdatedAt string `db:"updated_at" json:"updated_at"`
	UserID    string `db:"user_id" json:"user_id"`
	Coins_2   int64  `db:"coins_2" json:"coins_2"`
}

func (q *Queries) SpendUserCoins(ctx context.Context, arg SpendUserCoinsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, spendUserCoins,
		arg.Coins,
		arg.UpdatedAt,
		arg.UserID,
		arg.Coins_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchUser = `-- name: TouchUser :exec
UPDATE users
SET updated_at = ?
WHERE user_id = ?
`

type TouchUserParams struct {
	UpdatedAt string `db:"updated_at" json:"updated_at"`
	UserID    string `db:"user_id" json:"user_id"`
}

func (q *Queries) TouchUser(ctx context.Context, arg TouchUserParams) error {
	_, err := q.db.ExecContext(ctx, touchUser, arg.UpdatedAt, arg.UserID)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE users
SET
  name = ?,
  birth_date = ?,
  updated_at = ?
WHERE user_id = ?
`

type UpdateUserProfileParams struct {
	Name      string `db:"name" json:"name"`
	BirthDate string `db:"birth_date" json:"birth_date"`
	UpdatedAt string `db:"updated_at" json:"updated_at"`
	UserID    string `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateUserProfile,
		arg.Name,
		arg.BirthDate,
		arg.UpdatedAt,
		arg.UserID,
	)
	return err
}

const updateUserReferralRewardProgress = `-- name: UpdateUserReferralRewardProgress :exec
UPDATE users
SET
  referral_reward_progress = ?,
  updated_at = ?
WHERE user_id = ?
`

type UpdateUserReferralRewardProgressParams struct {
	ReferralRewardProgress float64 `db:"referral_reward_progress" json:"referral_reward_progress"`
	UpdatedAt              string  `db:"updated_at" json:"updated_at"`
	UserID                 string  `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateUserReferralRewardProgress(ctx context.Context, arg UpdateUserReferralRewardProgressParams) error {
	_, err := q.db.ExecContext(ctx, updateUserReferralRewardProgress, arg.ReferralRewardProgress, arg.UpdatedAt, arg.UserID)
	return err
}

const updateUserTheme = `-- name: UpdateUserTheme :exec
UPDATE users
SET
  theme = ?,
  updated_at = ?
WHERE user_id = ?
`

type UpdateUserThemeParams struct {
	Theme     string `db:"theme" json:"theme"`
	UpdatedAt string `db:"updated_at" json:"updated_at"`
	UserID    string `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateUserTheme(ctx context.Context, arg UpdateUserThemeParams) error {
	_, err := q.db.ExecContext(ctx, updateUserTheme, arg.Theme, arg.UpdatedAt, arg.UserID)
	return err
}
